import { createContext, useContext, useState } from 'react'

const translations = {
  en: {
    home: 'Home',
    products: 'Products',
    categories: 'Categories',
    adminLogin: 'Admin Login',
    dashboard: 'Dashboard',
    logout: 'Logout',
    orderWhatsApp: 'Order via WhatsApp',
    orderWhatsAppSub: 'Tap to chat with us on WhatsApp and place your order',
    view: 'View',
    quickView: 'Quick View',
    backToProducts: '← Back to Products',
    outOfStock: 'Out of Stock',
    inStock: 'in stock',
    description: 'Description',
    availability: 'Availability',
    sku: 'SKU',
    featuredProducts: 'Featured Products',
    handpicked: 'Handpicked For You',
    shopByCategory: 'Shop by Category',
    exploreRange: 'Explore Our Range',
    exploreCollection: 'Explore Collection',
    browseCategories: 'Browse Categories',
    viewAllProducts: 'View All Products',
    premiumSince: 'Premium Stationery Since 1995',
    heroTitle: 'Your Complete Stationery Store',
    heroSub: 'Discover our curated collection of premium stationery — from elegant pens to artisanal notebooks. Serving Bengaluru with love.',
    freeShipping: 'Free Delivery',
    freeShippingDesc: 'On orders above ₹500',
    premiumQuality: 'Premium Quality',
    premiumQualityDesc: 'Curated selections',
    giftWrapping: 'Gift Wrapping',
    giftWrappingDesc: 'Available on request',
    visitStore: 'Visit Store',
    visitStoreDesc: 'Bengaluru, Karnataka',
    ourStory: 'Our Story',
    aboutTitle: 'Quality Stationery, Trusted Since 1995',
    aboutP1: 'Kuldevi Stationery has been Bengaluru\'s trusted destination for premium writing instruments, artisanal notebooks, and office essentials for over 25 years.',
    aboutP2: 'Our carefully curated collection features timeless classics and modern innovations — making every visit a delight.',
    learnMore: 'Explore Our Products',
    ctaTitle: 'Looking for the Perfect Stationery?',
    ctaSub: 'Browse our collection and find pieces that inspire your creativity. Order via WhatsApp — simple and easy!',
    startBrowsing: 'Browse Products',
    quickLinks: 'Quick Links',
    contactUs: 'Contact Us',
    address: 'Kuldevi Stationery, Bengaluru, Karnataka - 560001',
    email: 'info@kuldevistationery.com',
    phone: '+91 98765 43210',
    copyright: 'Kuldevi Stationery. All rights reserved.',
    signingIn: 'Signing in...',
    signIn: 'Sign In',
    username: 'Username',
    password: 'Password',
    adminLoginTitle: 'Admin Login',
    invalidCreds: 'Invalid username or password',
    newProduct: 'Add New Product',
    loadingDash: 'Loading dashboard...',
    years: 'Years of Excellence',
  },
  kn: {
    home: 'ಮನೆ',
    products: 'ಉತ್ಪನ್ನಗಳು',
    categories: 'ವರ್ಗಗಳು',
    adminLogin: 'ನಿರ್ವಾಹಕ ಲಾಗಿನ್',
    dashboard: 'ಡ್ಯಾಶ್‌ಬೋರ್ಡ್',
    logout: 'ಲಾಗ್ ಔಟ್',
    orderWhatsApp: 'ವಾಟ್ಸ್ಆ್ಯಪ್‌ನಲ್ಲಿ ಆರ್ಡರ್ ಮಾಡಿ',
    orderWhatsAppSub: 'ವಾಟ್ಸ್ಆ್ಯಪ್‌ನಲ್ಲಿ ಚ್ಯಾಟ್ ಮಾಡಿ ಮತ್ತು ಆರ್ಡರ್ ನೀಡಿ',
    view: 'ನೋಡಿ',
    quickView: 'ತ್ವರಿತ ನೋಟ',
    backToProducts: '← ಉತ್ಪನ್ನಗಳಿಗೆ ಹಿಂತಿರುಗಿ',
    outOfStock: 'ಸ್ಟಾಕ್ ಇಲ್ಲ',
    inStock: 'ಸ್ಟಾಕ್‌ನಲ್ಲಿ ಇದೆ',
    description: 'ವಿವರಣೆ',
    availability: 'ಲಭ್ಯತೆ',
    sku: 'SKU',
    featuredProducts: 'ವಿಶೇಷ ಉತ್ಪನ್ನಗಳು',
    handpicked: 'ನಿಮಗಾಗಿ ಆಯ್ಕೆ ಮಾಡಿದವು',
    shopByCategory: 'ವರ್ಗ ಪ್ರಕಾರ ಖರೀದಿಸಿ',
    exploreRange: 'ನಮ್ಮ ಸಂಗ್ರಹ ನೋಡಿ',
    exploreCollection: 'ಸಂಗ್ರಹ ನೋಡಿ',
    browseCategories: 'ವರ್ಗಗಳು ನೋಡಿ',
    viewAllProducts: 'ಎಲ್ಲ ಉತ್ಪನ್ನಗಳು ನೋಡಿ',
    premiumSince: '೧೯೯೫ ರಿಂದ ಗುಣಮಟ್ಟದ ಸ್ಟೇಷನರಿ',
    heroTitle: 'ನಿಮ್ಮ ಸಂಪೂರ್ಣ ಸ್ಟೇಷನರಿ ಅಂಗಡಿ',
    heroSub: 'ಉತ್ತಮ ಪೆನ್, ನೋಟ್‌ಬುಕ್ ಮತ್ತು ಕಚೇರಿ ಸಾಮಗ್ರಿ. ಬೆಂಗಳೂರಿನ ನಿಮ್ಮ ಅಂಗಡಿ.',
    freeShipping: 'ಉಚಿತ ಡೆಲಿವರಿ',
    freeShippingDesc: '₹೫೦೦ ಮೇಲ್ಪಟ್ಟ ಆರ್ಡರ್‌ಗಳಿಗೆ',
    premiumQuality: 'ಉತ್ತಮ ಗುಣಮಟ್ಟ',
    premiumQualityDesc: 'ಆಯ್ಕೆ ಮಾಡಿದ ವಸ್ತುಗಳು',
    giftWrapping: 'ಉಡುಗೊರೆ ಪ್ಯಾಕಿಂಗ್',
    giftWrappingDesc: 'ವಿನಂತಿ ಮೇರೆಗೆ ಲಭ್ಯ',
    visitStore: 'ಅಂಗಡಿಗೆ ಭೇಟಿ ನೀಡಿ',
    visitStoreDesc: 'ಬೆಂಗಳೂರು, ಕರ್ನಾಟಕ',
    ourStory: 'ನಮ್ಮ ಕಥೆ',
    aboutTitle: 'ಗುಣಮಟ್ಟದ ಸ್ಟೇಷನರಿ, ೧೯೯೫ ರಿಂದ ನಂಬಿಕೆ',
    aboutP1: 'ಕುಲದೇವಿ ಸ್ಟೇಷನರಿ — ಬೆಂಗಳೂರಿನ ನಂಬಿಕೆಯ ಸ್ಟೇಷನರಿ ಅಂಗಡಿ. ೨೫ ವರ್ಷಗಳಿಂದ ಉತ್ತಮ ಬರವಣಿಗೆ ಸಾಮಗ್ರಿ, ನೋಟ್‌ಬುಕ್ ಮತ್ತು ಕಚೇರಿ ಸಾಮಗ್ರಿ ಒದಗಿಸುತ್ತಿದ್ದೇವೆ.',
    aboutP2: 'ನಮ್ಮ ಸಂಗ್ರಹದಲ್ಲಿ ಶ್ರೇಷ್ಠ ಮತ್ತು ಆಧುನಿಕ ವಸ್ತುಗಳಿವೆ — ಪ್ರತಿ ಬಾರಿ ಹೊಸದು ಸಿಗುತ್ತದೆ.',
    learnMore: 'ಉತ್ಪನ್ನಗಳು ನೋಡಿ',
    ctaTitle: 'ಸರಿಯಾದ ಸ್ಟೇಷನರಿ ಹುಡುಕುತ್ತಿದ್ದೀರಾ?',
    ctaSub: 'ನಮ್ಮ ಸಂಗ್ರಹ ನೋಡಿ ಮತ್ತು ನಿಮ್ಮ ಇಷ್ಟದ್ದು ಆಯ್ಕೆ ಮಾಡಿ. ವಾಟ್ಸ್ಆ್ಯಪ್‌ನಲ್ಲಿ ಆರ್ಡರ್ ಮಾಡಿ — ತುಂಬಾ ಸುಲಭ!',
    startBrowsing: 'ಉತ್ಪನ್ನಗಳು ನೋಡಿ',
    quickLinks: 'ತ್ವರಿತ ಲಿಂಕ್‌ಗಳು',
    contactUs: 'ಸಂಪರ್ಕಿಸಿ',
    address: 'ಕುಲದೇವಿ ಸ್ಟೇಷನರಿ, ಬೆಂಗಳೂರು, ಕರ್ನಾಟಕ - ೫೬೦೦೦೧',
    email: 'info@kuldevistationery.com',
    phone: '+91 98765 43210',
    copyright: 'ಕುಲದೇವಿ ಸ್ಟೇಷನರಿ. ಎಲ್ಲ ಹಕ್ಕುಗಳು ಕಾಯ್ದಿರಿಸಲಾಗಿದೆ.',
    signingIn: 'ಲಾಗಿನ್ ಆಗುತ್ತಿದೆ...',
    signIn: 'ಲಾಗಿನ್ ಮಾಡಿ',
    username: 'ಬಳಕೆದಾರ ಹೆಸರು',
    password: 'ಪಾಸ್‌ವರ್ಡ್',
    adminLoginTitle: 'ನಿರ್ವಾಹಕ ಲಾಗಿನ್',
    invalidCreds: 'ತಪ್ಪಾದ ಬಳಕೆದಾರ ಹೆಸರು ಅಥವಾ ಪಾಸ್‌ವರ್ಡ್',
    newProduct: 'ಹೊಸ ಉತ್ಪನ್ನ ಸೇರಿಸಿ',
    loadingDash: 'ಡ್ಯಾಶ್‌ಬೋರ್ಡ್ ಲೋಡ್ ಆಗುತ್ತಿದೆ...',
    years: 'ವರ್ಷಗಳ ಶ್ರೇಷ್ಠತೆ',
  }
}

const LangContext = createContext(null)

export function LangProvider({ children }) {
  const [lang, setLang] = useState('en')
  const t = (key) => translations[lang][key] ?? translations.en[key] ?? key
  const toggle = () => setLang(l => l === 'en' ? 'kn' : 'en')
  return (
    <LangContext.Provider value={{ lang, t, toggle }}>
      {children}
    </LangContext.Provider>
  )
}

export function useLang() {
  return useContext(LangContext)
}
